version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: banco_teste
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
 